### PR TITLE
feat: Added support for sub commands without group description

### PR DESCRIPTION
**Pull request by rowario**

### CODE REVIEW

**Comment by oceanroleplay** [comment]
fix build and add unit test.

**Comment by oceanroleplay** [comment]
Hey, I need the example usage.

**Comment by rowario** [comment]
image
image
image
image

here is example of how this is not working right now

**Comment by rowario** [comment]
> add unit test.
i'm not familiar with tests 😥, can we do something without that?

**Comment by oceanroleplay** [comment]
I am thankful for your effort and reporting this issue, this was supported early but I may have broken it somewhere in past and did not noticed yet.

Closing this in favour of https://github.com/oceanroleplay/discord.ts/pull/491/commits/553c25157ecb92390dea40a3e0652b95f88901d5

**Pull request closed without merging**
