### PR TITLE
docs: update README's

### PR DESCRIPTION
**Pull request by TeamWolfyta**
**Please describe the changes this PR makes and why it should be merged:**

Updating the README's

### CODE REVIEW

**Comment by oceanroleplay** [comment]
copy raw intnroducation

**Comment by TeamWolfyta** [comment]
> copy raw intnroducation

I did didn't I 🤔

**Comment by TeamWolfyta** [comment]
I was thinking about fully updating the README's, including the documentation but I'll leave that for when I look at the actual documentation.

**Comment by oceanroleplay** [comment]
I think, you should use raw table of packages as well.

**Comment by TeamWolfyta** [comment]
> I think, you should use raw table of packages as well.

I thought about that but it looked awful... Looks a lot better with bullet points as the sections below it also have bullet points...

**Comment by oceanroleplay** [comment]
> > I think, you should use raw table of packages as well.
> 
> I thought about that but it looked awful... Looks a lot better with bullet points as the sections below it also have bullet points...
> 
> Edit: I only just noticed there is a package table in discordx readme, Will have a look at it.

I understand but would be good to have description along with their names

**Comment by TeamWolfyta** [comment]
> > > I think, you should use raw table of packages as well.
> > 
> > 
> > I thought about that but it looked awful... Looks a lot better with bullet points as the sections below it also have bullet points...
> > Edit: I only just noticed there is a package table in discordx readme, Will have a look at it.
> 
> I understand but would be good to have description along with their names

Will do that now. [Discord Message of me asking](https://discord.com/channels/874802018361950248/876369442047660062/1007248250954326047)

**Comment by TeamWolfyta** [comment]
Let me know if you see something missing please.

**Comment by oceanroleplay** [comment]
capitalize typescript everywhere used, in it's actual format

**Comment by TeamWolfyta** [comment]
> capitalize typescript everywhere used, in it's actual format

Done

**Comment by oceanroleplay** [comment]
rever, `Discord.js` to `discord.js`

**Comment by TeamWolfyta** [comment]
> revert, `Discord.js` to `discord.js`

It's a name, Names start with capital letters.

**Comment by oceanroleplay** [comment]
> > revert, `Discord.js` to `discord.js`
> 
> It's a name, Names start with capital letters.

it's not, revert it please

**Comment by VictoriqueMoe** [comment]
> > revert, `Discord.js` to `discord.js`
> 
> It's a name, Names start with capital letters.

revert

**Comment by TeamWolfyta** [comment]
> > > revert, `Discord.js` to `discord.js`
> > 
> > 
> > It's a name, Names start with capital letters.
> 
> it's not, revert it please

Fine fine fine fine fine fine

**Comment by TeamWolfyta** [comment]
Did you want discordx lowercase ;-;

**Review by oceanroleplay — APPROVED** [review]

**Pull request merged**
